# Generated by Django 5.0 on 2026-02-17 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='poster',
            new_name='recruiter',
        ),
    ]
