# Generated by Django 6.0.3 on 2026-03-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_job_salary_max_remove_job_salary_min_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.TextField(help_text='Please list required skills here seperated by commas, eg. python, sql, java'),
        ),
    ]
