# Generated by Django 5.0 on 2026-02-17 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profile_about_me_profile_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('seeker', 'Job Seeker'), ('recruiter', 'Recruiter')], default='seeker', max_length=20),
        ),
    ]
