# Generated by Django 5.0 on 2026-02-19 04:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_profile_education_profile_github_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="show_about_me",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_contact_email",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_contact_phone",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_education",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_links",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_location",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_school_or_job",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_skills",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_work_experience",
            field=models.BooleanField(default=True),
        ),
    ]
