# Generated by Django 5.0 on 2026-03-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_profile_show_about_me_profile_show_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.TextField(blank=True, default='', help_text='Please list required skills here seperated by commas, eg. Python, SQL, JAVA'),
        ),
    ]
