# Generated by Django 5.0 on 2026-03-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_profile_city_profile_latitude_profile_longitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="commute_radius",
            field=models.IntegerField(default=50),
        ),
    ]
