# Generated by Django 5.0 on 2026-03-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notif_type",
            field=models.CharField(
                choices=[
                    ("message", "Message"),
                    ("recommendation", "Recommendation"),
                    ("login", "Login"),
                    ("saved_search", "Saved Search"),
                ],
                max_length=20,
            ),
        ),
    ]
